// src/server/domain/entities/financial-transaction.entity.test.ts
import { describe, it, expect } from "vitest";
import { FinancialTransaction } from "./financial-transaction.entity";

describe("FinancialTransaction Entity", () => {
    const validInput = {
        userId: "user-123",
        type: "INCOME" as const,
        amount: 5000000,
        category: "Salario",
        description: "Pago mensual",
        occurredAt: new Date("2026-03-01"),
        idempotencyKey: "key-abc-123",
    };

    it("should create a transaction with all required fields", () => {
        const tx = FinancialTransaction.create(validInput);

        expect(tx.userId).toBe("user-123");
        expect(tx.type).toBe("INCOME");
        expect(tx.amount).toBe(5000000);
        expect(tx.category).toBe("Salario");
        expect(tx.description).toBe("Pago mensual");
        expect(tx.occurredAt).toEqual(new Date("2026-03-01"));
        expect(tx.idempotencyKey).toBe("key-abc-123");
    });

    it("should default subtype to ORDINARY", () => {
        const tx = FinancialTransaction.create(validInput);
        expect(tx.subtype).toBe("ORDINARY");
    });

    it("should default currency to COP", () => {
        const tx = FinancialTransaction.create(validInput);
        expect(tx.currency).toBe("COP");
    });

    it("should default status to CONFIRMED", () => {
        const tx = FinancialTransaction.create(validInput);
        expect(tx.status).toBe("CONFIRMED");
    });

    it("should set source to null when not provided", () => {
        const tx = FinancialTransaction.create(validInput);
        expect(tx.source).toBeNull();
    });

    it("should use provided optional values", () => {
        const tx = FinancialTransaction.create({
            ...validInput,
            subtype: "EXTRAORDINARY",
            currency: "USD",
            source: "Empresa X",
        });

        expect(tx.subtype).toBe("EXTRAORDINARY");
        expect(tx.currency).toBe("USD");
        expect(tx.source).toBe("Empresa X");
    });

    it("should set empty id (will be generated by infrastructure)", () => {
        const tx = FinancialTransaction.create(validInput);
        expect(tx.id).toBe("");
    });

    it("should set registeredAt close to current time", () => {
        const before = new Date();
        const tx = FinancialTransaction.create(validInput);
        const after = new Date();

        expect(tx.registeredAt.getTime()).toBeGreaterThanOrEqual(before.getTime());
        expect(tx.registeredAt.getTime()).toBeLessThanOrEqual(after.getTime());
    });
});
