// src/server/domain/entities/financial-transaction.entity.ts
export type TransactionType = "INCOME" | "EXPENSE";
export type TransactionSubtype = "ORDINARY" | "EXTRAORDINARY";
export type TransactionStatus = "PENDING" | "CONFIRMED" | "CANCELLED";

export class FinancialTransaction {
    constructor(
        public readonly id: string,
        public readonly userId: string,
        public readonly type: TransactionType,
        public readonly subtype: TransactionSubtype,
        public readonly amount: number,
        public readonly currency: string,
        public readonly category: string,
        public readonly description: string,
        public readonly source: string | null,
        public readonly occurredAt: Date,
        public readonly registeredAt: Date,
        public readonly status: TransactionStatus,
        public readonly idempotencyKey: string,
    ) { }

    static create(data: {
        userId: string;
        type: TransactionType;
        subtype?: TransactionSubtype;
        amount: number;
        currency?: string;
        category: string;
        description: string;
        source?: string;
        occurredAt: Date;
        idempotencyKey: string;
    }): FinancialTransaction {
        return new FinancialTransaction(
            "", // ID will be generated by the infrastructure (Prisma)
            data.userId,
            data.type,
            data.subtype ?? "ORDINARY",
            data.amount,
            data.currency ?? "COP",
            data.category,
            data.description,
            data.source ?? null,
            data.occurredAt,
            new Date(),
            "CONFIRMED",
            data.idempotencyKey
        );
    }
}
